name: Context Demo

on: push

env:
  name: "jerin"

jobs:
  context-info:
    runs-on: ubuntu-latest
    env:
      address: "karnataka"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy -s settings.xml
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Verify JAR
        env:
          phone: "9072897543"
        run: |
          echo "the name is ${{ env.name }}"
          echo "the address is ${{ env.address }}"
          echo "the phone is $phone"
          ls -l target/
